// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikaelhg/comments-api/internal/dao (interfaces: CommentDao)
//
// Generated by this command:
//
//	mockgen -package=dao -destination=mocks_generated.go . CommentDao
//
// Package dao is a generated GoMock package.
package dao

import (
	gomock "go.uber.org/mock/gomock"
)

// MockCommentDao is a mock of CommentDao interface.
type MockCommentDao struct {
	ctrl     *gomock.Controller
	recorder *MockCommentDaoMockRecorder
}

// MockCommentDaoMockRecorder is the mock recorder for MockCommentDao.
type MockCommentDaoMockRecorder struct {
	mock *MockCommentDao
}

// NewMockCommentDao creates a new mock instance.
func NewMockCommentDao(ctrl *gomock.Controller) *MockCommentDao {
	mock := &MockCommentDao{ctrl: ctrl}
	mock.recorder = &MockCommentDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentDao) EXPECT() *MockCommentDaoMockRecorder {
	return m.recorder
}
